# define the `Secret` to define the necessary environment variables for the mongo server and mongo-express.
#username : root, psswd: root

apiVersion: v1
kind: Secret
metadata:
  name: secret
type: Opaque
data:
  mongo-root-username: 
  mongo-root-password: 